# Generated by Django 3.2.8 on 2021-11-11 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_item', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('squat', 'Squat'), ('pushup', 'Pushup'), ('plank', 'Plank')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='exercises.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='checklist',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='exercises.Checklist'),
        ),
    ]
