# Generated by Django 3.2.8 on 2021-11-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20211112_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='number',
            new_name='count_number',
        ),
    ]
