# Generated by Django 3.2.8 on 2021-11-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_rename_number_exercise_count_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_date_time',
        ),
        migrations.AddField(
            model_name='exercise',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
