# Generated by Django 3.2.8 on 2021-11-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20211112_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='check_item',
            new_name='check_item_name',
        ),
    ]
