# Generated by Django 3.2.8 on 2021-11-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_auto_20211112_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
