# Generated by Django 3.2.8 on 2021-11-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_auto_20211112_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motion',
            name='photo',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
