# Generated by Django 3.2.8 on 2021-11-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_alter_motion_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='feedback_check',
            field=models.BooleanField(default=False),
        ),
    ]
