# Generated by Django 3.2.8 on 2021-11-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_motion_feedback_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
