# Generated by Django 3.2.8 on 2021-12-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_auto_20211202_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='photo_back_checked',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
