# Generated by Django 3.2.8 on 2021-12-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_motion_photo_back_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
