# Generated by Django 3.2.8 on 2021-10-21 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('userid', models.CharField(default='', max_length=20)),
                ('userpassword', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('weight', models.IntegerField(default='0')),
                ('gender', models.TextField(default='Not Selected Yet')),
            ],
        ),
    ]
