# Generated by Django 3.2.8 on 2021-10-22 08:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='categori',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='feedback',
            name='count',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='score',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='apis.user'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=80)),
                ('file', models.ImageField(upload_to='')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='apis.feedback')),
            ],
        ),
    ]
